### ISSUE TITLE
Label size of eval_cityscapes_server.py

### ISSUE THREAD

**Issue by Serge-weihao** [xiaoyufenfei/LEDNet#14]
It seems that your code of eval_cityscapes_server.py produces labels with the resolution of 512X1024(not1024X2048). So I confused whether the Cityscapes test server can eval it correctly?

**Comment by xiaoyufenfei** [comment]
No problem, because the cityscape test set has no tags, online testing is required. You need to use the "eval_cityscapes_server.py" script with "--subset test" option which will produce the segmentation output for the 500 test images. Then you need to compress these images in a single ZIP and upload in their https://www.cityscapes-dataset.com/submit/ , which is the only way to get the result in the test set. also you can use the "eval_cityscapes_server.py" scripts with "--subset val" option to produce segments output for the val image, then, you can evaluate the **mIoU** using https://github.com/mcordts/cityscapesScripts/tree/master/cityscapesscripts/evaluation/ evalPixelLevelSemanticLabeling.py

**Comment by YN-Tang** [comment]
Glad to see you are finally answering to the issues.
But tbh I didn’t see where you answered the question. He asked how do you resolve your output resolution not in sync with test server, but what you said is how to use the test script and submit to test server.
Apologies if I didn’t get what you are saying.

**Comment by Serge-weihao** [comment]
> 
> Glad to see you are finally answering to the issues. But tbh I didn’t see where you answered the question. He asked how do you resolve your output resolution not in sync with test server, but what you said is how to use the test script and submit to test server. Apologies if I didn’t get what you are saying.
> […](#)
> 在 2019年7月27日，下午8:53，Yu Wang ***@***.***> 写道： Closed #14. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

@YN-Tang I find that the cityscapes server has an option of subsampling scale now and I didnt know it before. I think he may choosed scale at 2 when submitting, which is not common for us and he does not  emphasize in the paper.

**Comment by xiaoyufenfei** [comment]
Yes, as you said. If you train other networks and upload Cityscapes evaluations you won't have this problem.
